title: "圏論ノート"
summary: "圏論について勉強した内容をまとめる"
topics: ["category", "haskell", "mathematics"]
published: true
price: 0

# if the value for `chapters` set to empty,
# only the files named "{number}.{slug}.md" will be included in the book.
# https://zenn.dev/zenn/articles/zenn-cli-guide
